# Generated by Django 4.2.16 on 2024-09-19 06:59

import bimverse.models_utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='createdBy',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='createdFunction',
            field=models.CharField(default='admin', max_length=256),
        ),
        migrations.AddField(
            model_name='category',
            name='data',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='enableDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='errorText',
            field=models.TextField(blank=True, default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='geometry',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='hasError',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='identifier',
            field=models.CharField(blank=True, default='----', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='runFunctions',
            field=bimverse.models_utils.DataField(blank=True, default={}, help_text='{"functions": [{"function":"clearDataKeys","variables":{}}]}', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='uniqueCss',
            field=models.TextField(blank=True, default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='uniqueData',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='createdBy',
            field=models.CharField(default='default', max_length=256),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='createdFunction',
            field=models.CharField(default='admin', max_length=256),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='data',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='enableDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='errorText',
            field=models.TextField(blank=True, default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='geometry',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='hasError',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='identifier',
            field=models.CharField(blank=True, default='----', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='runFunctions',
            field=bimverse.models_utils.DataField(blank=True, default={}, help_text='{"functions": [{"function":"clearDataKeys","variables":{}}]}', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='uniqueCss',
            field=models.TextField(blank=True, default='', max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='uniqueData',
            field=bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
