# Generated by Django 4.2.16 on 2024-09-19 07:50

import bimverse.models_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0002_category_created_category_createdby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='edgeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-empty name-', max_length=256)),
                ('identifier', models.CharField(blank=True, default='----', max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hasError', models.BooleanField(default=False)),
                ('errorText', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('enableDelete', models.BooleanField(default=False)),
                ('createdBy', models.CharField(default='default', max_length=256)),
                ('createdFunction', models.CharField(default='admin', max_length=256)),
                ('uniqueCss', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('data', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('geometry', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('runFunctions', bimverse.models_utils.DataField(blank=True, default={}, help_text='{"functions": [{"function":"clearDataKeys","variables":{}}]}', max_length=9999, null=True)),
                ('uniqueData', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='nodeObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-empty name-', max_length=256)),
                ('identifier', models.CharField(blank=True, default='----', max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hasError', models.BooleanField(default=False)),
                ('errorText', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('enableDelete', models.BooleanField(default=False)),
                ('createdBy', models.CharField(default='default', max_length=256)),
                ('createdFunction', models.CharField(default='admin', max_length=256)),
                ('uniqueCss', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('data', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('geometry', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('runFunctions', bimverse.models_utils.DataField(blank=True, default={}, help_text='{"functions": [{"function":"clearDataKeys","variables":{}}]}', max_length=9999, null=True)),
                ('uniqueData', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
