# Generated by Django 4.2.16 on 2024-09-19 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0003_edgeobject_nodeobject_remove_ingredient_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeobject',
            name='nodeObject_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edgeFrom', to='bimverse.nodeobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edgeobject',
            name='nodeObject_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='edgeTo', to='bimverse.nodeobject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodeobject',
            name='connectedNodeObjects',
            field=models.ManyToManyField(through='bimverse.edgeObject', to='bimverse.nodeobject'),
        ),
    ]
