# Generated by Django 4.2.16 on 2024-09-20 01:44

import bimverse.models_utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0004_edgeobject_nodeobject_from_edgeobject_nodeobject_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='geometryObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-empty name-', max_length=256)),
                ('identifier', models.CharField(blank=True, default='----', max_length=200, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hasError', models.BooleanField(default=False)),
                ('errorText', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('enableDelete', models.BooleanField(default=False)),
                ('createdBy', models.CharField(default='default', max_length=256)),
                ('createdFunction', models.CharField(default='admin', max_length=256)),
                ('uniqueCss', models.TextField(blank=True, default='', max_length=9999, null=True)),
                ('isProcessed', models.BooleanField(default=False)),
                ('data', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('geometry', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('runFunctions', bimverse.models_utils.DataField(blank=True, default={}, help_text='{"functions": [{"function":"clearDataKeys","variables":{}}]}', max_length=9999, null=True)),
                ('uniqueData', bimverse.models_utils.DataField(blank=True, default={}, max_length=9999, null=True)),
                ('parentObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to='bimverse.nodeobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
