# Generated by Django 4.2.16 on 2024-09-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0005_geometryobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geometryobject',
            name='parentObject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometryObjects', to='bimverse.nodeobject'),
        ),
    ]
