# Generated by Django 4.2.16 on 2024-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0006_alter_geometryobject_parentobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='modularClassTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-empty name-', max_length=256)),
                ('connectedNodeObjects', models.ManyToManyField(to='bimverse.nodeobject')),
            ],
        ),
    ]
