# Generated by Django 4.2.16 on 2024-09-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0007_modularclasstag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularclasstag',
            name='connectedNodeObjects',
            field=models.ManyToManyField(blank=True, null=True, to='bimverse.nodeobject'),
        ),
    ]
