# Generated by Django 4.2.16 on 2024-09-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0009_alter_modularclasstag_connectednodeobjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modularclasstag',
            name='connectedNodeObjects',
        ),
        migrations.AddField(
            model_name='nodeobject',
            name='modularClassTags',
            field=models.ManyToManyField(blank=True, null=True, related_name='nodeObjects', to='bimverse.modularclasstag'),
        ),
    ]
