# Generated by Django 4.2.16 on 2024-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0010_remove_modularclasstag_connectednodeobjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularclasstag',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
