# Generated by Django 4.2.16 on 2024-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bimverse', '0012_edgeobject_project_nodeobject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeobject',
            name='dictionary',
            field=models.JSONField(default={'default': 'dictionary'}),
        ),
    ]
